######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 29 16:38:23 2015
######################################################################

QT+=opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GLPolygonWidget.h
SOURCES += GLPolygonMain.cpp GLPolygonWidget.cpp
